server:
  port:8080
spring:
  datasource:
    url: jdbc:hsqldb:mem:authdb
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password: pass
  jps:
    hibernate:
      ddl-auto:update
    show-sql: true