server:
  port:8080
spring:
  datasource:
    url: jdbc:hsqldb:mem:customersdb
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password:
  jps:
    hibernate:
      ddl-auto: update
    show-sql: true