server:
  port: 8081
spring:
  datasource:
    url: jdbc:hsqldb:mem:usersdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  security:
    user:
      password: none
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace